package main

import (
	"fmt"
	// "github.com/horobeanu/learnGO" is in go.mod file
	// which was generated by "go mod init github.com/horobeanu/learnGO" command
	"github.com/horobeanu/learnGO/entity"
)

// take a look on entity/user.go to see how things are defined
func main() {
	user := entity.NewUser()
	// we will get the pointer to a new empty "user" type
	fmt.Println(user)
	//&{0  }

	// de-reference to get data
	fmt.Println(*user)
	//{0  }

	// set user "FirstName" property
	user.FirstName = "Daniel"

	// access FirstName property and call GetPassword() method
	fmt.Println(user.FirstName, user.GetPassword())
	//Daniel
}
